#!/usr/bin/env python3
"""Output structure validator for tech-research pipeline.

Worker atom: QG-PROD-6 (output completeness)
Deterministic: file existence + content checks, no LLM needed.

Usage:
    python output_validator.py /path/to/docs/research/2026-03-28-slug/
"""

import os
import sys
import json
import re

REQUIRED_FILES = [
    "README.md",
    "00-query-original.md",
    "02-research-report.md",
    "03-recommendations.md",
]

OPTIONAL_FILES = [
    "01-deep-research-prompt.md",  # v4: prompt generated internally, file optional
    "metrics.yaml",                 # generated by metrics_collector.py post-write
    "pipeline-state.yaml",          # generated by metrics_collector.py save
    "execution-log.jsonl",          # generated by logger.py during pipeline
]

README_REQUIRED_SECTIONS = [
    "TL;DR",
    "Research Metadata",
    "coverage_score",
]

REPORT_MIN_SIZE = 500
RECS_MIN_SIZE = 200


def validate_output(output_dir: str) -> dict:
    """Validate research output directory structure and content."""
    results = {
        "directory": output_dir,
        "valid": True,
        "checks": [],
        "warnings": [],
        "errors": [],
    }

    if not os.path.isdir(output_dir):
        results["valid"] = False
        results["errors"].append(f"Directory not found: {output_dir}")
        return results

    for f in REQUIRED_FILES:
        path = os.path.join(output_dir, f)
        if os.path.exists(path):
            size = os.path.getsize(path)
            results["checks"].append({"file": f, "status": "EXISTS", "size": size})

            if f == "02-research-report.md" and size < REPORT_MIN_SIZE:
                results["warnings"].append(f"{f} is small ({size} bytes, min {REPORT_MIN_SIZE})")
            if f == "03-recommendations.md" and size < RECS_MIN_SIZE:
                results["warnings"].append(f"{f} is small ({size} bytes, min {RECS_MIN_SIZE})")
        else:
            results["valid"] = False
            results["errors"].append(f"MISSING required file: {f}")
            results["checks"].append({"file": f, "status": "MISSING"})

    for f in OPTIONAL_FILES:
        path = os.path.join(output_dir, f)
        if os.path.exists(path):
            results["checks"].append({"file": f, "status": "EXISTS", "size": os.path.getsize(path)})
        else:
            results["warnings"].append(f"Optional file missing: {f}")

    readme_path = os.path.join(output_dir, "README.md")
    if os.path.exists(readme_path):
        with open(readme_path) as f:
            content = f.read()
        for section in README_REQUIRED_SECTIONS:
            if section not in content:
                results["warnings"].append(f"README.md missing section/keyword: {section}")

    report_path = os.path.join(output_dir, "02-research-report.md")
    if os.path.exists(report_path):
        with open(report_path) as f:
            content = f.read()
        confidence_tags = len(re.findall(r"\[(?:HIGH|MEDIA|LOW)\s*—", content))
        if confidence_tags == 0:
            results["warnings"].append("02-research-report.md has no confidence tags [HIGH|MEDIA|LOW]")
        else:
            results["checks"].append({"check": "confidence_tags", "count": confidence_tags})

        source_dates = len(re.findall(r"—\s*\d{4}", content))
        results["checks"].append({"check": "source_dates_in_refs", "count": source_dates})

    follow_ups = [f for f in os.listdir(output_dir) if re.match(r"0[4-9]-.*\.md|[1-9]\d-.*\.md", f)]
    if follow_ups:
        results["checks"].append({"check": "follow_up_files", "count": len(follow_ups), "files": follow_ups})

    return results


def main():
    if len(sys.argv) < 2:
        print("Usage: output_validator.py <research_output_dir>", file=sys.stderr)
        sys.exit(1)

    result = validate_output(sys.argv[1])
    print(json.dumps(result, indent=2))

    if not result["valid"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
